<?php

declare(strict_types=1);

namespace Tests\Feature\Controllers;

use CodeIgniter\Test\FeatureTestCase;

/**
 * Class CalculateControllerTest
 *
 * @package Tests\Feature\Controllers
 */
class CalculateControllerTest extends FeatureTestCase
{
	protected function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	public function tearDown(): void
	{
		parent::tearDown(); // TODO: Change the autogenerated stub
	}

	/**
	 * @test
	 */
	public function 該当のページの文字列が表示されるべき(): void
	{
		$response = $this->get('/');
		$response->isOK();
		$response->assertSee('Welcome');
	}
}
